name: Frontend and Infrastructure CI-CD

on:
  workflow_dispatch:
    
      
  

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    permissions: read-all

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      # Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      # Install Yarn and build the frontend
      - name: Install Yarn and build frontend
        run: |
          npm install -g yarn
          cd Frontend
          yarn install
          yarn build
        
      
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectKey: "frontend-analysis"
          projectName: "frontend-analysis"
          projectVersion: "1.0"
          token: ${{ secrets.SONAR_TOKEN }}
          host: ${{ secrets.SONAR_HOST_URL }}
          sources: "Frontend/src"

      
      
     

         
